### ISSUE TITLE
eclipse URLs to be updated in get started page

### ISSUE THREAD

**Issue by dkimitsa** [MobiVM/mobivm.github.io#4]
_pages/getstarted.md

from:
```
    - [Eclipse plugin **Snapshot** update URL]()
    - [Eclipse plugin **Release** update URL]()
```

to 
```
    - [Eclipse plugin **Snapshot** update URL](https://mobivm.github.io/downloads.html?prefix=snapshots/eclipse)
    - [Eclipse plugin **Release** update URL](https://mobivm.github.io/downloads.html?prefix=releases/eclipse)
```

**Comment by dkimitsa** [comment]
update, it should point to bucket directly: https://mobivm.s3.eu-west-3.amazonaws.com/releases/eclipse/
also browser is not able to go to this link, so page should state this text directly

**Comment by crykn** [comment]
There is a PR pending for this: #3.

**Comment by Tom-Ski** [comment]
fixed by https://github.com/MobiVM/mobivm.github.io/pull/3
